const AUTOPREVIEW_CHECKBOX = "#autopreview";
const THEME_SELECT = "#theme-select";
const EDITOR_SELECT = "#editor";
const BOLD_BUTTON = ".format-toolbar--global [data-action='bold']";
const DESIGN_PAGE_SIZE = "#page-size";
const DESIGN_LINE_SPACING = "#line-spacing";
const DESIGN_ALIGNMENT = "#alignment";
const DESIGN_FONT_FAMILY = "#font-family";
const DESIGN_MARGIN_TOP = "#margin-top";
const DESIGN_MARGIN_BOTTOM = "#margin-bottom";
const DESIGN_MARGIN_LEFT = "#margin-left";
const DESIGN_MARGIN_RIGHT = "#margin-right";
const DESIGN_SHOW_FOOTER = "#show-footer";
const DESIGN_SHOW_TOP_NOTE = "#show-top-note";
const DESIGN_UNDERLINE_LINKS = "#underline-links";
const DESIGN_SHOW_EXTERNAL_LINK_ICON = "#show-external-link-icon";
